### ISSUE TITLE
Commentaires: placenames et placename_old_label

### ISSUE THREAD

**Issue by architexte** [chartes/dico-topo-app#1]
Les commentaires portent :
* sur un article
* sur un toponyme ancien
TODO:
* modifier le modèle (DB)
* reprendre l’insertion en base
* revoir l’affichage

Diagnostic, à partir de DT02 :
- 3161 commentaires au total (`//commentaire`)
- les commentaires peuvent suivre les éléments suivants – `distinct-values(//commentaire/preceding-sibling::*[1]/name())`
	- 1822 <forme_ancienne>	`//commentaire[preceding-sibling::*[1]/name() = 'forme_ancienne’]`
	- 1336 <definition>		`//commentaire[preceding-sibling::*[1]/name() = 'definition’]`
	- 3 <vedette>				`//commentaire[preceding-sibling::*[1]/name() = 'vedette']`

Proposition de règles :
- les commentaires qui suivent une <definition> ou une <vedette> se rapportent à l’entrée du dico (placename)
- les commentaires qui suivent une <forme_ancienne> se rapportent à cette forme ancienne

**Comment by architexte** [comment]
Décision OC/SN:
* Les commentaires portent TOUS sur l’article.
* Un article peut avoir par conséquent plusieurs commentaires.
* On affiche ces derniers à la fin de la notice -> TODO: être en mesure de les ordonner.
Pour la correction syntaxique, on se réfère à l’image de l’imprimé.

**Comment by MrGecko** [comment]
@architexte quel est le statut de cette issue ?

**Comment by architexte** [comment]
@MrGecko . Il est urgent de reprendre ça. Modification du modèle (plusieurs commentaires pour un lieu) et code de chargement en base !

**Comment by architexte** [comment]
Done
