### ISSUE TITLE
Sourcer les toponymes

### ISSUE THREAD

**Issue by architexte** [chartes/dico-topo-app#14]
Prévoir l’évolution du modèle utile au référencement bibliographique de chaque toponyme (`placename` et `placename_old_label` ), en vue de l’intégration de toponymes issus d’autres sources que le DT (par ex. les Pouillés).

**Comment by MrGecko** [comment]
cf #29 et l'affichage de la référence biblio.
Doit-il y avoir une page de description de la source biblio ?
Quel est le modèle (côté base) décrivant cette soure ?

**Comment by architexte** [comment]
Il conviendra de lier chaque `place_old_label` à un `bibl`.
Cette table `bibl` devra être suffisamment générique pour décrire à la fois des livres (métadonnées bibliographiques) et des fonds d’archives…

**Comment by MrGecko** [comment]
voir la branche **multisourceV2** pour le travail en cours

**Comment by architexte** [comment]
Done. Ajout de `responsability` au modèle.
