### ISSUE TITLE
Recherche de formes – cas "molendinum"

### ISSUE THREAD

**Issue by architexte** [chartes/dico-topo-app#2]
Recherche de formes (toponymiques).
1. Obtenir toutes les formes (label d’article, forme alternative de ce label et formes anciennes) qui contiennent "molendinum"
2. Pouvoir filtrer le résultat:
  * selon la géographie administrative
  * par date (quand possible)
  * par typologie
  * et pouvoir visualiser les points correspondants sur la carte
  * et pouvoir exporter le résultat filtré (pour les chercheurs)
3. pouvoir lister toutes les "formes vedettes" de l’ensemble de formes composant ce résultat: c'est-à-dire lister les articles dans lesquels on trouve au moins une forme ancienne "molendinum". Selon SN, c’est la base: trouver tous les articles contenant la forme ancienne "molendinum".

**Comment by MrGecko** [comment]
J'aimerais scinder ce ticket en plusieurs issues.

**Comment by MrGecko** [comment]
@architexte : je pense qu'il faudrait réévaluer et scinder cette issue en conséquence

**Comment by MrGecko** [comment]
cf #43 pour l'export

**Comment by architexte** [comment]
@MrGecko . Issue en effet trop floue et en partie résolue. On ferme !
