### ISSUE TITLE
Recherche – diacritiques

### ISSUE THREAD

**Issue by architexte** [chartes/dico-topo-app#20]
Rendre par défaut la recherche insensible aux diacritiques.  
Proposer un switch (*sensitive*/*insensitive*) ?

**Comment by MrGecko** [comment]
cf #21

**Comment by MrGecko** [comment]
@architexte : Peux-tu me donner quelques cas de test ?

**Comment by MrGecko** [comment]
Fait côté API,
Manque le switch côté Frontend pour passer de l'analyseur standard à l'analyzeur folding (field.folded)

**Comment by architexte** [comment]
Recherche insensible aux diacritiques. Documenté en ligne.
