### ISSUE TITLE
Recherche – analyzer

### ISSUE THREAD

**Issue by architexte** [chartes/dico-topo-app#21]
Bien définir l’interprétation des chaînes recherchées, notamment :
- gestion des apostrophes droites (`'`) et courbes (`’`) ;
- gestion du `œ` | `oe` ;
- ?

**Comment by MrGecko** [comment]
@architexte : Je pense qu'il faudrait toujours illustrer ce genre de cas par des exemples concrets (pour éviter que je prenne le problème à l'envers)

**Comment by MrGecko** [comment]
Comportement actuel :  on peut utiliser les apostrophes courbes ou droites indifférement lors de la recherche. L'analyzer d'elasticsearch est configuré pour redresser les apostrophes lors de l'indexation et lors de la recherche

**Comment by MrGecko** [comment]
Dépend de #20
