### ISSUE TITLE
Recherche – tableau des résultats

### ISSUE THREAD

**Issue by architexte** [chartes/dico-topo-app#23]
Reprendre le formatage des données dans le tableau des résultats de recherche pour optimiser l’affichage écran :
- Fer gauche pour les en-têtes de colonne.
- Compacter les colonnes qui peuvent l’être :
	- Remplacer le label `Localisation` par l’icône correspondante
	- Remplacer le label `Département` par `Dép.` + travailler la largeur du filtre (imprimer le seul code)
	- Resserrer espace entre les icônes de filtre et de tri
- `Formes anciennes`
	- liste en pleine ligne, avec ` ; ` comme séparateur. 
	- ajouter la date entre parenthèses après chaque forme ancienne.
	- ordonner les formes anciennes par ordre chronologique.
	- imprimer les formes en romain.
- Description
	- couper la description au caractère 60 + `…` ;
	- afficher toute la description dans une bulle au survol
- Ajouter une colonne triable `commune` qui renvoie le label INSEE de la première commune citée en localisation.
- Supprimer l’icône de téléchargement

Ordre des colonnes en vue *Lieux* :
- Localisation
- Lieu
- Forme ancienne
- Département
- Commune
- Description
- Liage
Ordre des colonnes en vue *Toponymes* :
Idem, avec permutation des colonnes Toponyme et Lieu.

Limiter le tableaux à 200 lignes de résultats.

Réduire la hauteur du bas de tableau (pagination).

Attention à la gestion des diacritiques pour les tris !

**Comment by MrGecko** [comment]
A-t-on vraiment besoin de la colonne liage dans le tableau de résultat ? Ca fait potentiellement des centaines de boutons en plus. Le bloc "Utiliser cette donnée" sur la page du lieu me paraît plus pratique.

**Comment by architexte** [comment]
@MrGecko D’accord pour la suppression de l’icône de liage.
Penser à tester l’ajout du filtre par canton.
Suggestion : rendre la colonne COMMUNE filtrable ?

**Comment by architexte** [comment]
Done
