### ISSUE TITLE
Mise à jour de la documentation

### ISSUE THREAD

**Issue by MrGecko** [chartes/dico-topo-app#26]
- Ajouter plus d'exemple
- Montrer les exports
- Mieux documenter chaque champ

**Comment by MrGecko** [comment]
@architexte je pense qu'il faudrait aussi rendre les dépots du projets moins austères et remplir les guidelines : [https://github.com/chartes/dico-topo-app/community](https://github.com/chartes/dico-topo-app/community)

**Comment by architexte** [comment]
Documentation rédigée. Reprendre les repo.
