### ISSUE TITLE
Structuration et formatage de la fiche de l’entité

### ISSUE THREAD

**Issue by architexte** [chartes/dico-topo-app#29]
Page: `https://dicotopo.cths.fr/placenames/<id>`

Structure ordonnée de la fiche :
1. Label
1. La hiérarchie administrative (Dpt > (Arrondissement >)? Ville > Lieu-dit) dans la zone grisée du label
1. Référence biblio abrégée et cliquable, par ex. : "DT76, 1982, p. n"
1. Définition
1. Liste des formes anciennes (sur une unique ligne avec le toponyme en noir, non tronquées, non répétées, triées par ordre chronologique, non cliquables ; liste ouverte par défaut)
1. Idéalement, proposer un lien vers la table des abréviations, sous le label "Formes anciennes" -> suppose reprise du modèle et inscription en base des références de ces pages (sont-elles d’ailleurs disponibles ?)
1. Commentaire (fermé par défaut)
1. Lieux liés (fermé par défaut)

Enrichissements typographique :
- Small caps
- Italique
- ?

NB1. Penser l’affichage du bloc avec les liages.  
NB2. Pouvoir remonter de la fiche lieu-dit à la fiche de la commune de rattachement.

**Comment by MrGecko** [comment]
@architexte quid des formes alternatives ?

**Comment by MrGecko** [comment]
@architexte : 3) comment est construit le champ ? que fait le lien cliquable ?

**Comment by architexte** [comment]
@MrGecko 

3) cf #42. La modification du modèle est faite, la base utile aux tests générée. Le lien doit donner accès à l’image (visionneuse IIIF qui convoque le manifest Gallica).

8) cf #30. Il s’agit des lieux localisés dans la même commune ; pour le terme à adopter côté API (#36), `linked-place` est pas mal. Il faudrait voir si un vocabulaire partagé (type Getty) permet de mieux décrire cette relation.

Formes alternatives. A placer selon moi au plus près du Label, puisqu’il ne s’agit pas de formes anciennes référencées, mais de simples labels alternatifs.

**Comment by architexte** [comment]
@MrGecko 
2 remarques complémentaires 

1. Comment garantir le tri des formes anciennes par date (par ex ci-dessous, "IXe siècle") ?
2. Penser à bien rendre la mise en forme typographique, notamment les sc.

<img width="680" alt="Capture d’écran 2020-04-21 à 18 28 37" src="https://user-images.githubusercontent.com/29038322/79889324-25f58280-83fe-11ea-877a-79e9388b12ba.png">
