### ISSUE TITLE
Items de la liste "lieux liés" des notices (fiche entité)

### ISSUE THREAD

**Issue by architexte** [chartes/dico-topo-app#30]
Objectif:
1. Pour une commune : fournir la liste des lieux contenus dans cette commune – par ex., pour Laon (DT02-03131), sortir Chauny (DT02-01379) de la liste des lieux liés.
1. Pour un lieux-dit : fournir la liste des seuls lieux-dits situés aussi dans sa commune de rattachement (ou uniquement la commune de rattachement ?)

**Comment by MrGecko** [comment]
J'ai du mal à voir comment on naviguera entre Laon et Chauny (doit-on même pouvoir naviguer entre les deux ?)

**Comment by MrGecko** [comment]
@architexte il faudrait réussir à trancher pour le point 2 (j'aime bien fermer les issues)

**Comment by architexte** [comment]
@MrGecko : je ne procéderais pas ainsi. La hiérarchie administrative (Chauny > Arbre de Saint-Éloi) sera indiquée dans le fil d’Ariane.

- pour le point 1 (cas commune) : lister tous les lieux dépendant de la commune (déjà fait), par ex. pour Laon : 
<img width="680" alt="Capture d’écran 2020-04-21 à 17 58 18" src="https://user-images.githubusercontent.com/29038322/79886720-bb424800-83f9-11ea-9c5c-f57ca6498d88.png">

- pour le point 2 (cas d’un lieu localisé dans la commune) : lister tous les **autres** lieux qui se trouvent localisés dans cette même commune. Docn, même liste que point 1 (moins le lieu courant, càd le lieu affiché, ici Avin). Et non la commune d’appartenance, Laon :

<img width="681" alt="Capture d’écran 2020-04-21 à 18 01 54" src="https://user-images.githubusercontent.com/29038322/79887016-53d8c800-83fa-11ea-983d-49f0d392a60e.png">

Pour mieux expliciter le contenu de cette rubrique, il faut en redéfinir le titre, par ex. : "Autre(s) lieu(x) à Laon"
