### ISSUE TITLE
Liage INSEE

### ISSUE THREAD

**Issue by architexte** [chartes/dico-topo-app#32]
Pour OC, lier si possible chaque entité à la page de référence INSEE.
Par ex. DT76-14806 / https://www.insee.fr/fr/metadonnees/cog/commune/COM76351-le-havre

**Comment by MrGecko** [comment]
Il faudrer lister les tâches à effectuer du style :
- [ ] Analyser la couverture du liage
- [ ] Mettre à jour le modèle et l'API
- [ ] Ajouter le lien dans le bloc "Sur le web"

**Comment by architexte** [comment]
https://www.insee.fr/fr/recherche/recherche-geographique?geo=COM-{code-insee}
https://www.insee.fr/fr/recherche/recherche-geographique?geo=COM-76476
