### ISSUE TITLE
API géoportail

### ISSUE THREAD

**Issue by architexte** [chartes/dico-topo-app#33]
Rebrancher les fonds de cartes historiques.

**Comment by MrGecko** [comment]
1) Bug d'import du module geoportail. Probablement un problème de configuration du projet
2) Voir si notre clef doit être renouvelée
3) Réévaluer le comportement du fond de carte

**Comment by MrGecko** [comment]
Le rollback vers la version **2.0.1** de **geoportal-extensions-leaflet** semble résoudre certains problèmes.
