### ISSUE TITLE
Ajouter une liseuse IIIF sur la page détaillée

### ISSUE THREAD

**Issue by MrGecko** [chartes/dico-topo-app#42]
Ajouter une liseuse IIIF sur la page détaillée et afficher la page de début de l'article

**Comment by architexte** [comment]
Idée : affichage des pages Gallica.
TODO: travail de liage de la donnée (pb => ark Gallica)

**Comment by architexte** [comment]
cf branch [gallica-link](https://github.com/chartes/dico-topo-app/tree/gallica-link).

**Comment by architexte** [comment]
@MrGecko, @Corentinfaye 
Le lien de la référence de l’article (par ex. `DT02, p. n`) appelle la visionneuse IIIF.
3 comportements possibles :

1. Le dictionnaire n’est pas disponible sur Gallica: la référence de l’article n’est pas cliquable (rien ne se passe).
2. Le dictionnaire est disponible sur Gallica, mais les images ne sont pas disponibles via le serveur IIIF (`gallica_IIIF_availability` à 0): la référence de l’article est cliquable et permet d’ouvrir dans un nouvel onglet la visionneuse Gallica à la bonne page, par ex. : https://gallica.bnf.fr/ark:/12148/bpt6k367437/f120.image
3. Le dictionnaire est disponible sur Gallica et les images sont disponibles via le serveur IIIF (`gallica_IIIF_availability` à 1): la référence de l’article est cliquable et convoque dans la page notre visionneuse IIIF avec le DT à la bonne page.

**Comment by MrGecko** [comment]
> Le dictionnaire n’est pas disponible sur Gallica: la référence de l’article n’est pas cliquable (rien ne se passe).

Cela correspond au cas où le champ `gallica_ark` est vide ?
