### ISSUE TITLE
Ajouter un bouton "aller vers la carte"

### ISSUE THREAD

**Issue by MrGecko** [chartes/dico-topo-app#52]
Je pense qu'il est peut-être nécessaire d'ajouter un bouton "rechercher" ou "aller vers la carte" en plus du fait d'appuyer sur entrée dans la barre de recherche.
Il y a des cas lors de la navigation où on ne sait pas comment retourner vers la carte (ex; on fait une recherche puis on va sur la page contact).

Si on ajoute un bouton, cela signifie qu'on abandonne la recherche "en direct" lors de la saisie.
Ça peut être intéressant, notamment pour des raisons de performance (aujourd'hui faut attendre 0.5s sans taper pour que la recherche se déclenche).

**Comment by architexte** [comment]
@MrGecko. D’accord, 2 avantages :
- on conserve le tableau des résultats tant qu’une nouvelle requête n’est pas envoyée.
- meilleures perfs.
